apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: appt-deploy
spec:
  selector:
    matchLabels:
      app: appt-service
  replicas: 1
  template:
    metadata:
      labels:
        app: appt-service
    spec:
      containers:
      - name: appt-service
        image: aptregistry.azurecr.io/flexidoctor:latest

